"""
Configuration for Linear Rotation-Accumulation Experiment

Tests whether Agent can discover left-to-right (l2r) temporal order
from sequences generated by orthogonal matrix dynamics.
"""

# ===== Task Configuration =====
# Linear dynamical system: h_{t+1} = R @ h_t + x_t, x_{t+1} = argmax(h_{t+1})
vocab_size = 128          # Vocabulary size V (small enough for speed, large enough to split)
seq_length = 6            # Sequence length L (easy mode - search space is 6!=720)
hidden_dim = 128          # Hidden dimension D (MUST equal vocab_size for physics)
ortho_mode = 'random'     # 'random' (Haar measure) or 'permutation'
block_size = 6            # Must match sequence length

# Fixed R matrix configuration (ensures same physics across all samples)
fixed_R_path = 'linear_rotation_exp/fixed_R.pt'
# OOD Split: train on tokens 0-99, validate on NEVER-SEEN tokens 100-127
train_start_tokens = list(range(0, 100))      # 100 sequences for train (start tokens 0-99)
val_start_tokens = list(range(100, 128))      # 28 sequences for val (start tokens 100-127, NEVER seen in training)

# ===== Model Configuration =====
# Standard architecture for sequence modeling
n_layer = 3               # Number of transformer layers
n_head = 4                # Number of attention heads
n_embd = 128              # Embedding dimension
model_type = 'AdaLN6_NoRep_cond_128_trunc_qknorm'
dropout = 0.0
bias = True

# ===== Training Configuration =====
batch_size = 64           # Standard size for faster training
learning_rate = 1e-3      # Model learning rate
max_iters = 20000         # Total training iterations
warmup_steps = 2000       # Warmup steps for learning rate
grad_clip = 1.0           # Gradient clipping

# Dataset
train_mode = 'static'      # 'static' (pre-generated) - use fixed R matrix
num_train_samples = 10000  # Virtual epoch size (samples train sequences repeatedly)
num_val_samples = 1000     # Validation samples (always static)
num_test_samples = 1000    # Test samples (always static)
dataset_seed = 42

# ===== Agent Configuration =====
agent_learning_rate = 1e-4  # Agent learning rate (lower for stable policy learning)
policy_dim = 128            # Agent hidden dimension

# Reward type: 'log_prob' (continuous) or 'binary' (0/1)
reward_type = 'log_prob'

# REINFORCE baseline (variance reduction)
use_baseline = True

# Teacher Forcing (guide agent to learn correct order)
teacher_forcing_start = 1.0      # Start with 100% forcing
teacher_forcing_end = 0.0        # Decay to 0% forcing
teacher_forcing_decay_steps = 5000   # Faster decay since task is easier with seq_length=6

# Dense Step-wise Rewards (immediate feedback for correct token selection)
use_stepwise_rewards = True      # Enable dense rewards
stepwise_reward_weight = 2.0     # Weight for step-wise correctness (alpha)

# Behavior Cloning (BC) Loss for Agent (supervised signal even when TF=0)
use_bc_loss = True               # Enable BC loss for agent
bc_loss_weight = 2.0             # Weight for BC loss (stronger supervised signal)

# ===== Logging Configuration =====
log_interval = 10          # Log every N steps
eval_interval = 100        # Evaluate every N steps
checkpoint_interval = 500  # Save checkpoint every N steps

# Weights & Biases
wandb_log = True
wandb_project = 'LO-ARMs-LinearRotation'
wandb_run_name = f'rotation_V{vocab_size}_L{seq_length}_OOD'

# Output directory
out_dir = 'linear_rotation_exp/checkpoints'

# ===== Device Configuration =====
device = 'cuda'  # Use 'cuda' if available, else 'cpu'
dtype = 'bfloat16' if device == 'cuda' else 'float32'
compile = False

# ===== Optimizer Configuration =====
beta1 = 0.9
beta2 = 0.95
weight_decay = 0.1

# ===== Evaluation Configuration =====
eval_iters = 100  # Number of batches for evaluation

# ===== Expected Results =====
#
# Agent should discover the LEFT-TO-RIGHT (l2r) temporal order:
#   Given: tokens = [t0, t1, t2, ..., t_{L-1}] (generated by dynamical system)
#   Goal: Learn order = [0, 1, 2, ..., L-1] (select t0 first, t1 second, ..., t_{L-1} last)
#
# Expected metrics evolution:
#
#   First Step - Should select t0:
#     first_step/p_t0:  ~5% (random) → >90% (learned)
#
#   Second Step - Should select t1:
#     second_step/p_t1: ~5% (random) → >85% (learned)
#
#   Last Step - Should select t_{L-1}:
#     last_step/p_tL:   ~5% (random) → >90% (learned)
#
#   Overall Order Correctness:
#     l2r_order_correct: ~0% (random) → >80% (learned)
#     kendall_tau:       ~0 (random) → >0.9 (learned)
#
#   Model Performance:
#     accuracy:          ~6% (random) → >75% (learned)
#     loss:              ~2.8 (ln(16)) → <0.5 (learned)
#
#   Reconstruction Error:
#     recon_error:       ~10 (random) → <1 (learned)
#
# Why this task is hard:
#   - No positional encoding (Agent must learn order from dynamics)
#   - Long-range dependencies (all history matters via R^k)
#   - Orthogonal R creates complex state trajectories
#   - Bag input provides no order information
#
# This experiment validates:
#   1. Agent can discover temporal order without explicit supervision
#   2. Model can learn long-range dependencies via state accumulation
#   3. System handles complex linear dynamics (orthogonal transformations)
#   4. Training converges despite large search space (20! orderings)

# ===== Experiment Variants =====

# Variant 1: Larger vocabulary (if Phase 0 uniqueness was marginal)
# vocab_size = 32
# hidden_dim = 32
# wandb_run_name = 'rotation_V32_L20'

# Variant 2: Longer sequences (harder task)
# seq_length = 30
# block_size = 30
# max_iters = 15000
# warmup_steps = 3000
# wandb_run_name = 'rotation_V16_L30'

# Variant 3: Permutation matrix (sparser dynamics)
# ortho_mode = 'permutation'
# wandb_run_name = 'rotation_V16_L20_perm'

# Variant 4: Larger model (if convergence is slow)
# n_layer = 4
# n_embd = 256
# policy_dim = 256
# wandb_run_name = 'rotation_V16_L20_large'

# Variant 5: Binary reward (for comparison)
# reward_type = 'binary'
# wandb_run_name = 'rotation_V16_L20_binary'
