"""
Test Suite for Linear Dynamical System Data Generator

Unit tests and quality validation for Phase 0.
"""

import numpy as np
from collections import Counter
from data_generator import LinearDynamicalGenerator


def test_ortho_matrix():
    """Verify orthogonal matrix property: R^T @ R = I"""
    print("Test 1: Orthogonal Matrix Property")

    for mode in ['random', 'permutation']:
        generator = LinearDynamicalGenerator(vocab_size=16, hidden_dim=16, ortho_mode=mode, seed=42)
        R = generator.R

        # Check R^T @ R = I
        product = R.T @ R
        identity = np.eye(16)
        is_orthogonal = np.allclose(product, identity, atol=1e-5)

        print(f"  Mode '{mode}': Orthogonal = {is_orthogonal}")
        assert is_orthogonal, f"Matrix is not orthogonal in mode {mode}!"

    print("  ✅ PASSED\n")


def test_generate_sequence_basic():
    """Test basic sequence generation logic"""
    print("Test 2: Basic Sequence Generation")

    generator = LinearDynamicalGenerator(vocab_size=16, hidden_dim=16, ortho_mode='random', seed=42)

    # Generate a sequence
    result = generator.generate_sequence(length=10, start_token_id=0, mode='argmax')

    tokens = result['tokens']
    bag = result['bag']
    states = result['states']

    # Check length
    assert len(tokens) == 10, f"Expected length 10, got {len(tokens)}"

    # Check all tokens are valid
    for t in tokens:
        assert 0 <= t < 16, f"Invalid token {t}"

    # Check bag is consistent
    assert sum(bag.values()) == 10, "Bag count mismatch"
    for token in tokens:
        assert token in bag, f"Token {token} not in bag"

    # Check states length
    assert len(states) == 10, f"Expected 10 states, got {len(states)}"

    print(f"  Generated sequence: {tokens[:5]}... (length {len(tokens)})")
    print(f"  Bag: {dict(bag)}")
    print("  ✅ PASSED\n")


def test_verify_uniqueness_logic():
    """Test the uniqueness verification logic"""
    print("Test 3: Uniqueness Verification Logic")

    generator = LinearDynamicalGenerator(vocab_size=8, hidden_dim=8, ortho_mode='random', seed=123)

    # Generate a valid sequence
    result = generator.generate_sequence(length=5, start_token_id=0, mode='argmax')
    tokens = result['tokens']

    # Verify it
    is_valid, is_unique = generator.verify_uniqueness(tokens)

    print(f"  Tokens: {tokens}")
    print(f"  Valid: {is_valid}, Unique: {is_unique}")

    # Should be valid (generated by argmax)
    assert is_valid, "Generated sequence should be valid!"

    print("  ✅ PASSED\n")


def test_margin_computation():
    """Test margin computation"""
    print("Test 4: Margin Computation")

    generator = LinearDynamicalGenerator(vocab_size=8, hidden_dim=8, ortho_mode='random', seed=456)

    # Generate sequence
    result = generator.generate_sequence(length=6, start_token_id=0, mode='argmax')
    tokens = result['tokens']

    # Compute margins
    margins = generator.compute_margin(tokens)

    print(f"  Sequence length: {len(tokens)}")
    print(f"  Margins computed: {len(margins)}")
    print(f"  Sample margins: {[f'{m:.3f}' for m in margins[:3]]}")

    # Check margins
    assert len(margins) == len(tokens) - 1, "Margin count mismatch"
    assert all(m >= 0 for m in margins), "Margins should be non-negative"

    print("  ✅ PASSED\n")


def test_different_vocab_sizes():
    """Test with different vocabulary sizes"""
    print("Test 5: Different Vocabulary Sizes")

    for V in [8, 16, 32]:
        generator = LinearDynamicalGenerator(vocab_size=V, hidden_dim=V, ortho_mode='random', seed=789)
        result = generator.generate_sequence(length=10, start_token_id=0, mode='argmax')

        tokens = result['tokens']
        is_valid, is_unique = generator.verify_uniqueness(tokens)

        print(f"  V={V:2d}: Valid={is_valid}, Unique={is_unique}, Tokens={tokens[:3]}...")

    print("  ✅ PASSED\n")


def test_deterministic_with_seed():
    """Test that same seed produces same results"""
    print("Test 6: Deterministic Behavior with Seed")

    # Generate twice with same seed
    gen1 = LinearDynamicalGenerator(vocab_size=16, hidden_dim=16, ortho_mode='random', seed=999)
    result1 = gen1.generate_sequence(length=10, start_token_id=0, mode='argmax')

    gen2 = LinearDynamicalGenerator(vocab_size=16, hidden_dim=16, ortho_mode='random', seed=999)
    result2 = gen2.generate_sequence(length=10, start_token_id=0, mode='argmax')

    tokens1 = result1['tokens']
    tokens2 = result2['tokens']

    print(f"  Run 1: {tokens1}")
    print(f"  Run 2: {tokens2}")

    assert tokens1 == tokens2, "Same seed should produce same sequence"

    print("  ✅ PASSED\n")


def run_all_tests():
    """Run all unit tests"""
    print("=" * 60)
    print("🧪 Running Unit Tests for Linear Dynamical Generator")
    print("=" * 60)
    print()

    tests = [
        test_ortho_matrix,
        test_generate_sequence_basic,
        test_verify_uniqueness_logic,
        test_margin_computation,
        test_different_vocab_sizes,
        test_deterministic_with_seed
    ]

    for test in tests:
        try:
            test()
        except Exception as e:
            print(f"  ❌ FAILED: {e}\n")
            return False

    print("=" * 60)
    print("✅ All Unit Tests Passed!")
    print("=" * 60)
    print()
    return True


if __name__ == '__main__':
    # Run unit tests first
    tests_passed = run_all_tests()

    if not tests_passed:
        print("⚠️  Unit tests failed, skipping quality check")
        import sys
        sys.exit(1)

    # Run main quality check
    print("Proceeding to Phase 0 Quality Check...\n")
    from data_generator import main
    success = main()

    import sys
    sys.exit(0 if success else 1)
