"""
LO-ARMs Training Script for Linear Rotation-Accumulation Experiment

Tests whether Agent can discover left-to-right (l2r) temporal order from
sequences generated by orthogonal matrix dynamics.

Two-phase training:
1. Warmup: Train model with random orders (frozen agent)
2. Co-evolution: Train both model and agent with REINFORCE

Expected Result:
- Agent should learn l2r order: [0, 1, 2, ..., L-1]
- P(select_t0_first) should converge to ~100%
- P(select_t_{L-1}_last) should converge to ~100%
- l2r_order_correct should converge to >80%
"""

import os
import sys
import time
import math
import torch
import torch.nn.functional as F
import numpy as np
from scipy.stats import kendalltau

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import components
from linear_rotation_exp.rotation_dataset import create_dataloaders
from lossy_copy_exp.model_wrapper import AOGPTWithHiddenStates
from lossy_copy_exp.order_policy_net import OrderPolicyNet
from lossy_copy_exp.utils import (
    compute_accuracy,
    compute_returns,
    normalize_returns,
    MetricsTracker,
    save_checkpoint,
    log_metrics,
    create_experiment_dir,
    save_config
)
from model_AOGPT_AdaLN6_NoRep_cond_128_trunc_qknorm import AOGPTConfig

# Import config
import linear_rotation_exp.config_rotation as config


def compute_rotation_metrics(actions_list, seq_length=20):
    """
    Compute comprehensive metrics for linear rotation task.

    Key metrics:
    - first_step/p_t0: Agent selects t0 first
    - second_step/p_t1: Agent selects t1 second
    - last_step/p_tL: Agent selects t_{L-1} last
    - l2r_order_correct: Complete l2r order [0,1,2,...,L-1] is correct
    - kendall_tau: Rank correlation with ground truth l2r order

    Args:
        actions_list: List of [B] tensors, one per step
        seq_length: Sequence length L

    Returns:
        Dictionary with detailed metrics
    """
    metrics = {}
    B = actions_list[0].shape[0]
    device = actions_list[0].device

    # First step: Should select t0 (position 0)
    first_actions = actions_list[0]  # [B]
    metrics['first_step/p_t0'] = (first_actions == 0).float().mean().item()

    # Second step: Should select t1 (position 1)
    if len(actions_list) > 1:
        second_actions = actions_list[1]  # [B]
        metrics['second_step/p_t1'] = (second_actions == 1).float().mean().item()

    # Third step: Should select t2 (position 2)
    if len(actions_list) > 2:
        third_actions = actions_list[2]  # [B]
        metrics['third_step/p_t2'] = (third_actions == 2).float().mean().item()

    # Last step: Should select t_{L-1}
    if len(actions_list) >= seq_length:
        last_actions = actions_list[-1]  # [B]
        metrics[f'last_step/p_t{seq_length-1}'] = (last_actions == seq_length - 1).float().mean().item()

    # Reconstruct full order from actions
    # actions[t] indicates which logical position was filled at step t
    # We want to compute the order: order[i] = step when position i was filled
    reconstructed_orders = torch.zeros(B, seq_length, dtype=torch.long, device=device)
    for step, actions in enumerate(actions_list):
        reconstructed_orders[torch.arange(B), actions] = step

    # Ground truth l2r order: [0, 1, 2, ..., L-1]
    # This means position 0 filled at step 0, position 1 at step 1, etc.
    ground_truth_order = torch.arange(seq_length, device=device).unsqueeze(0).expand(B, -1)

    # Check if complete order is correct (l2r)
    l2r_correct = (reconstructed_orders == ground_truth_order).all(dim=1).float().mean().item()
    metrics['l2r_order_correct'] = l2r_correct

    # Compute Kendall's tau (rank correlation)
    kendall_taus = []
    for b in range(B):
        order_b = reconstructed_orders[b].cpu().numpy()
        gt_order_b = ground_truth_order[b].cpu().numpy()
        tau, _ = kendalltau(order_b, gt_order_b)
        if not np.isnan(tau):
            kendall_taus.append(tau)

    metrics['kendall_tau'] = np.mean(kendall_taus) if kendall_taus else 0.0

    # Reconstruction error (L1 distance between orders)
    recon_error = (reconstructed_orders - ground_truth_order).abs().float().mean().item()
    metrics['reconstruction_error'] = recon_error

    return metrics


def get_batch(dataloader_iter, dataloader, device):
    """
    Get next batch from dataloader, handling epoch boundaries.

    Args:
        dataloader_iter: Iterator for dataloader
        dataloader: DataLoader object
        device: Device to move data to

    Returns:
        batch: Dictionary with tensors moved to device
        dataloader_iter: Updated iterator
    """
    try:
        batch = next(dataloader_iter)
    except StopIteration:
        # Restart iterator at epoch boundary
        dataloader_iter = iter(dataloader)
        batch = next(dataloader_iter)

    # Move to device (except bag which is Counter)
    batch_on_device = {}
    for k, v in batch.items():
        if k == 'bag':
            batch_on_device[k] = v  # Keep as list of Counters
        else:
            batch_on_device[k] = v.to(device)

    return batch_on_device, dataloader_iter


def warmup_step(model, optimizer_model, batch):
    """
    Warmup training step: train model with random orders.

    Args:
        model: AOGPTWithHiddenStates
        optimizer_model: Model optimizer
        batch: Data batch

    Returns:
        metrics: Dictionary of metrics
    """
    model.train()

    tokens = batch['tokens']  # [B, L]
    logical_ids = batch['logical_ids']  # [B, L]

    # Random orders
    orders = model.sample_random_orders(tokens)

    # Forward pass
    logits, loss = model.forward_with_hidden(
        tokens, orders, logical_ids=logical_ids, return_hidden_states=False
    )

    # Backward pass
    optimizer_model.zero_grad()
    loss.backward()

    # Gradient clipping
    if config.grad_clip > 0:
        torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip)

    optimizer_model.step()

    # Compute metrics
    acc = compute_accuracy(logits, tokens)

    return {
        'loss': loss.item(),
        'accuracy': acc,
    }


def coevolution_step(model, agent, optimizer_model, optimizer_agent, batch, device, global_step=0):
    """
    Co-evolution training step: train both model and agent.

    Uses REINFORCE algorithm with continuous rewards (log probabilities).
    Includes Teacher Forcing to guide the agent during early training.

    Args:
        model: AOGPTWithHiddenStates
        agent: OrderPolicyNet
        optimizer_model: Model optimizer
        optimizer_agent: Agent optimizer
        batch: Data batch
        device: Device
        global_step: Current training step (for teacher forcing decay)

    Returns:
        metrics: Dictionary of metrics
    """
    model.train()
    agent.train()

    tokens = batch['tokens']  # [B, L]
    logical_ids = batch['logical_ids']  # [B, L]
    unshuffled_tokens = batch['unshuffled_tokens']  # [B, L]
    B, L = tokens.shape

    # Compute teacher forcing ratio (linear decay)
    if global_step < config.teacher_forcing_decay_steps:
        tf_ratio = config.teacher_forcing_start - (config.teacher_forcing_start - config.teacher_forcing_end) * (
            global_step / config.teacher_forcing_decay_steps
        )
    else:
        tf_ratio = config.teacher_forcing_end

    # ===== Phase 1: Rollout with Agent (with Teacher Forcing) =====
    # Start with empty sequence and iteratively fill positions

    # Initialize filled mask (0=available, 1=filled)
    filled_mask = torch.zeros(B, L, device=device)

    # Partial tokens (start with placeholders)
    partial_tokens = torch.zeros(B, L, dtype=torch.long, device=device)

    # Track actions and log probs for REINFORCE
    actions_list = []
    log_probs_list = []
    rewards_list = []
    agent_logits_list = []  # For BC loss

    # Generated order (which position to fill at each step)
    generated_order = torch.zeros(B, L, dtype=torch.long, device=device)

    for step in range(L):
        # Get current order so far (for positions already filled)
        current_order = generated_order.clone()

        # Get hidden states from current partial sequence
        with torch.no_grad():
            _, _, hidden_states = model.forward_with_hidden(
                partial_tokens,
                current_order,
                logical_ids=logical_ids,
                return_hidden_states=True
            )

        # Agent selects next position to fill (get logits for BC loss)
        use_bc = getattr(config, 'use_bc_loss', False)
        if use_bc:
            actions, log_probs, agent_logits = agent.sample_action(hidden_states, filled_mask, return_logits=True)
            agent_logits_list.append(agent_logits)
        else:
            actions, log_probs = agent.sample_action(hidden_states, filled_mask)

        # Teacher Forcing: Override with correct action with probability tf_ratio
        # Ground truth l2r order: step 0 -> position 0, step 1 -> position 1, etc.
        if tf_ratio > 0:
            # Determine which samples to force
            force_mask = torch.rand(B, device=device) < tf_ratio

            # Correct action for this step is to select position 'step'
            correct_actions = torch.full((B,), step, dtype=torch.long, device=device)

            # Override actions where force_mask is True
            actions = torch.where(force_mask, correct_actions, actions)

        # Store for REINFORCE
        actions_list.append(actions)
        log_probs_list.append(log_probs)

        # Update generated order
        generated_order[torch.arange(B), actions] = step

        # Fill selected positions with true tokens (from unshuffled)
        for b in range(B):
            action_b = actions[b].item()
            partial_tokens[b, action_b] = unshuffled_tokens[b, action_b]

        # Mark position as filled
        filled_mask[torch.arange(B), actions] = 1

        # ===== Compute Reward =====
        # Combines two types of rewards:
        # 1. Prediction reward: How well the model predicts the token
        # 2. Step-wise reward: Whether the agent picked the correct position (L2R order)

        # Get model predictions with current partial sequence
        logits, _ = model.forward_with_hidden(
            partial_tokens,
            generated_order,
            logical_ids=logical_ids,
            return_hidden_states=False
        )

        # Get log probabilities
        log_probs_model = F.log_softmax(logits, dim=-1)  # [B, L+1, vocab_size]

        # For each filled position, compute log prob of correct token
        batch_indices = torch.arange(B, device=device)

        # Get correct tokens
        correct_tokens = unshuffled_tokens[batch_indices, actions]
        pred_logits = log_probs_model[batch_indices, actions, correct_tokens]

        # REWARD COMPONENT 1: Prediction reward (from model accuracy)
        if config.reward_type == 'log_prob':
            prediction_reward = pred_logits
        elif config.reward_type == 'binary':
            # Binary reward: 1 if correct, 0 if wrong
            preds = logits[batch_indices, actions, :].argmax(dim=-1)
            prediction_reward = (preds == correct_tokens).float()
        else:
            raise ValueError(f"Unknown reward type: {config.reward_type}")

        # REWARD COMPONENT 2: Step-wise reward (immediate feedback for correct order)
        if config.use_stepwise_rewards:
            # Ground truth L2R order: step 0 should select position 0, step 1 -> position 1, etc.
            correct_position = step
            stepwise_reward = (actions == correct_position).float()  # 1.0 if correct, 0.0 if wrong

            # Combine both rewards with weighting
            total_reward = prediction_reward + config.stepwise_reward_weight * stepwise_reward
        else:
            # Use only prediction reward
            total_reward = prediction_reward

        rewards_list.append(total_reward)

    # ===== Phase 2: REINFORCE Update for Agent =====
    # Compute returns
    returns = compute_returns(rewards_list, mode='immediate')

    # Normalize returns (variance reduction)
    if config.use_baseline:
        returns = normalize_returns(returns)

    # Compute policy loss
    policy_loss = 0
    for log_prob, ret in zip(log_probs_list, returns):
        policy_loss += -(log_prob * ret.detach()).mean()
    policy_loss = policy_loss / L  # Average over steps

    # ===== Behavior Cloning (BC) Loss =====
    # Supervised signal to guide agent toward correct L2R order
    bc_loss = torch.tensor(0.0, device=device)
    use_bc = getattr(config, 'use_bc_loss', False)
    bc_weight = getattr(config, 'bc_loss_weight', 1.0)

    if use_bc and len(agent_logits_list) > 0:
        # Stack agent logits: [L, B, num_positions]
        stacked_logits = torch.stack(agent_logits_list, dim=0)  # [L, B, L]

        # Ground truth: at step t, correct action is position t (L2R order)
        # Create targets: [L, B] where targets[t, :] = t for all batches
        targets = torch.arange(L, device=device).unsqueeze(1).expand(L, B)  # [L, B]

        # Compute cross-entropy loss
        # Reshape for cross_entropy: logits [L*B, num_positions], targets [L*B]
        bc_loss = F.cross_entropy(
            stacked_logits.view(L * B, -1),  # [L*B, num_positions]
            targets.reshape(-1)  # [L*B]
        )

    # Total agent loss = policy_loss + bc_weight * bc_loss
    total_agent_loss = policy_loss + bc_weight * bc_loss

    # Update agent
    optimizer_agent.zero_grad()
    total_agent_loss.backward()

    # Gradient clipping for agent
    if config.grad_clip > 0:
        torch.nn.utils.clip_grad_norm_(agent.parameters(), config.grad_clip)

    optimizer_agent.step()

    # ===== Phase 3: Supervised Update for Model =====
    # Train model with true tokens and generated order
    logits_model, loss_model = model.forward_with_hidden(
        unshuffled_tokens,
        generated_order.detach(),  # Detach to avoid backprop through agent
        logical_ids=logical_ids,
        return_hidden_states=False
    )

    # Update model
    optimizer_model.zero_grad()
    loss_model.backward()

    # Gradient clipping
    if config.grad_clip > 0:
        torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip)

    optimizer_model.step()

    # ===== Compute Metrics =====
    # Rotation-specific selection metrics
    rotation_metrics = compute_rotation_metrics(actions_list, seq_length=L)

    # Model accuracy
    acc = compute_accuracy(logits_model, unshuffled_tokens)

    # Average reward
    avg_reward = torch.stack(rewards_list).mean().item()

    # Step-wise correctness (how often agent picks correct position at each step)
    if config.use_stepwise_rewards:
        stepwise_correct = []
        for step, actions in enumerate(actions_list):
            correct_position = step
            correct_rate = (actions == correct_position).float().mean().item()
            stepwise_correct.append(correct_rate)
        avg_stepwise_correct = sum(stepwise_correct) / len(stepwise_correct)
    else:
        avg_stepwise_correct = 0.0

    metrics = {
        'loss': loss_model.item(),
        'policy_loss': policy_loss.item(),
        'accuracy': acc,
        'avg_reward': avg_reward,
        'tf_ratio': tf_ratio,  # Track teacher forcing ratio
        'avg_stepwise_correct': avg_stepwise_correct,  # Track step-wise correctness
    }

    # Add BC loss if enabled
    if use_bc:
        metrics['loss_agent_bc'] = bc_loss.item()

    metrics.update(rotation_metrics)

    return metrics


@torch.no_grad()
def evaluate(model, agent, dataloader, device, eval_iters=100):
    """
    Evaluate model and agent.

    Args:
        model: AOGPTWithHiddenStates
        agent: OrderPolicyNet
        dataloader: Validation dataloader
        device: Device
        eval_iters: Number of batches to evaluate

    Returns:
        metrics: Dictionary of evaluation metrics
    """
    model.eval()
    agent.eval()

    metrics_tracker = MetricsTracker()
    dataloader_iter = iter(dataloader)

    for _ in range(min(eval_iters, len(dataloader))):
        try:
            batch, dataloader_iter = get_batch(dataloader_iter, dataloader, device)

            tokens = batch['tokens']
            logical_ids = batch['logical_ids']
            unshuffled_tokens = batch['unshuffled_tokens']
            B, L = tokens.shape

            # Rollout with agent
            filled_mask = torch.zeros(B, L, device=device)
            partial_tokens = torch.zeros(B, L, dtype=torch.long, device=device)
            generated_order = torch.zeros(B, L, dtype=torch.long, device=device)
            actions_list = []
            rewards_list = []

            for step in range(L):
                current_order = generated_order.clone()

                _, _, hidden_states = model.forward_with_hidden(
                    partial_tokens,
                    current_order,
                    logical_ids=logical_ids,
                    return_hidden_states=True
                )

                actions, _ = agent.sample_action(hidden_states, filled_mask)
                actions_list.append(actions)

                generated_order[torch.arange(B), actions] = step

                for b in range(B):
                    action_b = actions[b].item()
                    partial_tokens[b, action_b] = unshuffled_tokens[b, action_b]

                filled_mask[torch.arange(B), actions] = 1

                # Compute reward
                logits, _ = model.forward_with_hidden(
                    partial_tokens,
                    generated_order,
                    logical_ids=logical_ids,
                    return_hidden_states=False
                )

                log_probs_model = F.log_softmax(logits, dim=-1)
                batch_indices = torch.arange(B, device=device)
                correct_tokens = unshuffled_tokens[batch_indices, actions]
                pred_logits = log_probs_model[batch_indices, actions, correct_tokens]
                rewards_list.append(pred_logits)

            # Final model evaluation
            logits_model, loss_model = model.forward_with_hidden(
                unshuffled_tokens,
                generated_order,
                logical_ids=logical_ids,
                return_hidden_states=False
            )

            # Compute metrics
            rotation_metrics = compute_rotation_metrics(actions_list, seq_length=L)
            acc = compute_accuracy(logits_model, unshuffled_tokens)
            avg_reward = torch.stack(rewards_list).mean().item()

            batch_metrics = {
                'loss': loss_model.item(),
                'accuracy': acc,
                'avg_reward': avg_reward,
            }
            batch_metrics.update(rotation_metrics)

            metrics_tracker.update(**batch_metrics)

        except StopIteration:
            break

    return metrics_tracker.get_all_means()


def get_lr(iteration, warmup_steps, max_iters, learning_rate):
    """
    Learning rate schedule with linear warmup and cosine decay.

    Args:
        iteration: Current iteration
        warmup_steps: Number of warmup steps
        max_iters: Total iterations
        learning_rate: Peak learning rate

    Returns:
        lr: Learning rate for this iteration
    """
    # Linear warmup
    if iteration < warmup_steps:
        return learning_rate * (iteration + 1) / warmup_steps

    # Cosine decay
    decay_ratio = (iteration - warmup_steps) / (max_iters - warmup_steps)
    decay_ratio = max(0, min(1, decay_ratio))
    coeff = 0.5 * (1.0 + math.cos(math.pi * decay_ratio))
    return learning_rate * coeff


def main():
    """Main training loop."""
    print("=" * 60)
    print("🚀 Linear Rotation-Accumulation Experiment")
    print("=" * 60)
    print()

    # Create experiment directory
    exp_dir = create_experiment_dir(config.out_dir, config.wandb_run_name)
    print(f"📁 Experiment directory: {exp_dir}")

    # Save config
    save_config(config, exp_dir)

    # Create serializable config dict (for both wandb and checkpointing)
    config_dict = {
        k: v for k, v in vars(config).items()
        if not k.startswith('_') and isinstance(v, (int, float, str, bool, list, dict, type(None)))
    }

    # Initialize wandb
    wandb_run = None
    if config.wandb_log:
        import wandb

        wandb_run = wandb.init(
            project=config.wandb_project,
            name=exp_dir,
            config=config_dict
        )

    # Set device
    device = torch.device(config.device if torch.cuda.is_available() else 'cpu')
    print(f"🔧 Device: {device}")

    # Create dataloaders
    print("\n📊 Creating datasets...")

    # Check for fixed R configuration
    fixed_R_path = getattr(config, 'fixed_R_path', None)
    train_start_tokens = getattr(config, 'train_start_tokens', None)
    val_start_tokens = getattr(config, 'val_start_tokens', None)

    if fixed_R_path:
        print(f"Using fixed R matrix from: {fixed_R_path}")
        print(f"Train start tokens: {len(train_start_tokens) if train_start_tokens else 'None'}")
        print(f"Val start tokens: {len(val_start_tokens) if val_start_tokens else 'None'}")

    train_loader, val_loader, test_loader = create_dataloaders(
        vocab_size=config.vocab_size,
        seq_length=config.seq_length,
        hidden_dim=config.hidden_dim,
        ortho_mode=config.ortho_mode,
        train_samples=config.num_train_samples,
        val_samples=config.num_val_samples,
        test_samples=config.num_test_samples,
        batch_size=config.batch_size,
        num_workers=0,
        seed=config.dataset_seed,
        train_mode=config.train_mode,
        fixed_R_path=fixed_R_path,
        train_start_tokens=train_start_tokens,
        val_start_tokens=val_start_tokens
    )

    # Initialize model
    print("\n🤖 Initializing model...")
    model_config = AOGPTConfig(
        block_size=config.block_size,
        vocab_size=config.vocab_size,
        n_layer=config.n_layer,
        n_head=config.n_head,
        n_embd=config.n_embd,
        dropout=config.dropout,
        bias=config.bias
    )
    model = AOGPTWithHiddenStates(model_config).to(device)
    print(f"   Parameters: {sum(p.numel() for p in model.parameters()) / 1e6:.2f}M")

    # Initialize agent
    print("\n🧠 Initializing agent...")
    agent = OrderPolicyNet(
        d_model=config.n_embd,
        policy_dim=config.policy_dim,
        num_positions=config.seq_length
    ).to(device)
    print(f"   Parameters: {sum(p.numel() for p in agent.parameters()) / 1e6:.2f}M")

    # Initialize optimizers
    optimizer_model = torch.optim.AdamW(
        model.parameters(),
        lr=config.learning_rate,
        betas=(config.beta1, config.beta2),
        weight_decay=config.weight_decay
    )

    optimizer_agent = torch.optim.AdamW(
        agent.parameters(),
        lr=config.agent_learning_rate,
        betas=(config.beta1, config.beta2),
        weight_decay=0.0  # No weight decay for agent
    )

    # Training loop
    print("\n" + "=" * 60)
    print("🎯 Starting Training")
    print("=" * 60)

    train_iter = iter(train_loader)
    metrics_tracker = MetricsTracker()
    start_time = time.time()

    for iteration in range(config.max_iters):
        # Get batch
        batch, train_iter = get_batch(train_iter, train_loader, device)

        # Update learning rates
        lr_model = get_lr(iteration, config.warmup_steps, config.max_iters, config.learning_rate)
        lr_agent = get_lr(iteration, config.warmup_steps, config.max_iters, config.agent_learning_rate)

        for param_group in optimizer_model.param_groups:
            param_group['lr'] = lr_model
        for param_group in optimizer_agent.param_groups:
            param_group['lr'] = lr_agent

        # Training step
        if iteration < config.warmup_steps:
            # Phase A: Warmup (train model only)
            metrics = warmup_step(model, optimizer_model, batch)
            phase = 'warmup'
        else:
            # Phase B: Co-evolution (train both, with teacher forcing)
            metrics = coevolution_step(
                model, agent, optimizer_model, optimizer_agent, batch, device,
                global_step=iteration - config.warmup_steps  # TF decay starts from 0 after warmup
            )
            phase = 'coevolution'

        metrics['lr_model'] = lr_model
        metrics['lr_agent'] = lr_agent

        metrics_tracker.update(**metrics)

        # Logging
        if (iteration + 1) % config.log_interval == 0:
            avg_metrics = metrics_tracker.get_all_means()
            elapsed = time.time() - start_time
            tokens_per_sec = config.batch_size * config.seq_length * config.log_interval / elapsed

            print(f"[{iteration + 1:5d}/{config.max_iters}] "
                  f"Loss: {avg_metrics['loss']:.4f} | "
                  f"Acc: {avg_metrics['accuracy']:.3f} | "
                  f"Phase: {phase} | "
                  f"Tok/s: {tokens_per_sec:.0f}")

            if config.wandb_log:
                log_metrics(avg_metrics, iteration + 1, phase='train', wandb_run=wandb_run)

            metrics_tracker.reset()
            start_time = time.time()

        # Evaluation
        if (iteration + 1) % config.eval_interval == 0:
            print(f"\n📊 Evaluating at iteration {iteration + 1}...")
            eval_metrics = evaluate(model, agent, val_loader, device, config.eval_iters)

            print(f"   Val Loss: {eval_metrics['loss']:.4f}")
            print(f"   Val Acc: {eval_metrics['accuracy']:.3f}")
            print(f"   First Step p(t0): {eval_metrics.get('first_step/p_t0', 0):.3f}")
            print(f"   L2R Correct: {eval_metrics.get('l2r_order_correct', 0):.3f}")
            print(f"   Kendall Tau: {eval_metrics.get('kendall_tau', 0):.3f}")

            if config.wandb_log:
                log_metrics(eval_metrics, iteration + 1, phase='val', wandb_run=wandb_run)

        # Checkpointing
        if (iteration + 1) % config.checkpoint_interval == 0:
            save_checkpoint(
                model, agent,
                optimizer_model, optimizer_agent,
                iteration + 1,
                config_dict,
                exp_dir
            )
            print(f"💾 Saved checkpoint: {exp_dir}/checkpoint_{iteration + 1}.pt")

    # Final evaluation
    print("\n" + "=" * 60)
    print("🏁 Final Evaluation")
    print("=" * 60)

    test_metrics = evaluate(model, agent, test_loader, device, len(test_loader))
    print(f"\nTest Results:")
    print(f"   Loss: {test_metrics['loss']:.4f}")
    print(f"   Accuracy: {test_metrics['accuracy']:.3f}")
    print(f"   First Step p(t0): {test_metrics.get('first_step/p_t0', 0):.3f}")
    print(f"   L2R Order Correct: {test_metrics.get('l2r_order_correct', 0):.3f}")
    print(f"   Kendall Tau: {test_metrics.get('kendall_tau', 0):.3f}")
    print(f"   Reconstruction Error: {test_metrics.get('reconstruction_error', 0):.3f}")

    if config.wandb_log and wandb_run is not None:
        log_metrics(test_metrics, config.max_iters, phase='test', wandb_run=wandb_run)
        wandb_run.finish()

    # Save final checkpoint
    save_checkpoint(
        model, agent,
        optimizer_model, optimizer_agent,
        config.max_iters,
        config_dict,
        exp_dir
    )
    print(f"\n💾 Saved final checkpoint: {exp_dir}/checkpoint_{config.max_iters}.pt")
    print("\n✅ Training complete!")


if __name__ == '__main__':
    main()
